[ant]
stepsize = 7
ini_energy = 10
energy_to_create_new_ant = 50

[environment]
width = 500
height = 500

[nest]
ini_foodqty = 49

[pheromone]
persistence = 100
qty_ph_upon_foodfind = 30

[graphics]
ant.radius = 2
ant.scouting_colour = "#3BC302"  # Other option: "#AF0220"
ant.scouting_lowhealth_colour = "#FFC000"
ant.scouting_criticalhealth_colour = "#C00000"
ant.notscouting_colour = "#5B9BD5"  # Other option: "#3BC302"
environment.backgroundcolour = "#F4F2F0"  # Dark mode: "#000028"
food.ini_colour = "#00C8C8"
nest.radius = 20
nest.colour = "#F27E1D"
pheromone.radius = 0.1
pheromone.colour = "#050994"

